### ISSUE TITLE
Creating routing such that a unique url is created for each user and can be shared to other users.

### ISSUE THREAD

**Issue by benjaminhr** [benjaminr177/editor#1]
Currently there is only the homepage which can be shared, it would be useful to create unique urls for sharing documents.

**Comment by uLan08** [comment]
Seems that everything is anonymous at the moment. How would you like to approach this? Perhaps, first just giving out unique id's for each created markdown that are not really tied to a user.

**Comment by benjaminhr** [comment]
This seems like a good solution, implement it! Doesn't need to be anything super complex.

**Comment by benjaminhr** [comment]
Did you get the project running locally? Any problems?

**Comment by uLan08** [comment]
Node modules were committed into the repository. I'll remove them,

**Comment by jmdelcarmen** [comment]
Got it working :) 
https://github.com/benjaminr177/editor/pull/2

**Comment by benjaminhr** [comment]
@uLan08 Should be in the .gitignore already.. weird. Thanks for removing them though!

**Comment by benjaminhr** [comment]
@jmdelcarmen I'll wait for @uLan08's PR and then I'll compare implementations. Thank you for contributing though 🍻

**Comment by jmdelcarmen** [comment]
@benjaminr177  woops. forgot to import the `utils.js` script into the `pad.ejs`.
a simple `<script src="utils.js"></script>` should do.

**Comment by uLan08** [comment]
@benjaminr177 I was planning to make it on the backend. It makes much more sense to me if it's there.

**Comment by benjaminhr** [comment]
@uLan08 That does make sense, I would prefer to keep client and server-side distinctly separate.

**Comment by jmdelcarmen** [comment]
@uLan08 adding backend logic makes no sense. Document retrieval takes place on the client. There is no fancy async operations happening on the backend, Redis handles everything.

**Comment by benjaminhr** [comment]
Okay so, I merged with @jmdelcarmen branch since it doesn't really matter in this case whether it is in the client or server-side, as long as it works.

**Comment by uLan08** [comment]
@jmdelcarmen It's not about that. You're handling creation of uuid's to the frontend, and for me that is insecure.

**Comment by uLan08** [comment]
@benjaminr177 Alright. I'll continue working on my solution if you're still interested.

**Comment by benjaminhr** [comment]
@uLan08 Sure! I'd love to see your implementation still.

**Comment by uLan08** [comment]
@benjaminr177 Glad to hear that. I almost have the route working. I am just not too sure how to integrate it with redis.

**Comment by benjaminhr** [comment]
I don't think you need to
