### ISSUE TITLE
Create unit tests for the project

### ISSUE THREAD

**Issue by benjaminhr** [benjaminr177/editor#3]
Throw some ideas on how you would go around this, what tools would you use, etc.

**Comment by jonyeezs** [comment]
For something small like this i would recommend:
* [Mocha](https://mochajs.org/) - framework
  * has nice cli features off the bat.
  * Heavily used by the community
  * And would work with travis if you ever want to automate
* [Supertest](https://github.com/visionmedia/supertest)
  * Allows to stub your express server
* [JSDOM-Global](https://github.com/rstacruz/jsdom-global)
  * allows us to run our test in a fake DOM environment. Mocks `document` and `window`

If we are focusing on unit test, these should be enough to cover all 3 js files.

For an E2E test, I haven't thought of the best way, as I'm not familiar on ejs.
But I believe Supertest could proof it could support it.

**Comment by benjaminhr** [comment]
E2E testing can be left out, I'll do that myself, but the rest sounds perfect.

Let me know if you need help with the setup in your local environment!

**Comment by jonyeezs** [comment]
I'm gonna have a go at this :weight_lifting_man:

**Comment by jonyeezs** [comment]
@benjaminr177 something i didn't realise.
utils uses iife. That's going to be difficult to test with a node unit test framework (which is almost all).

We'll have to use a web bundler for this. What would you prefer? I'm thinking of using ~rollup as that is really easy to use without needing any configs~ browserify as rollup doesn't support node's `require` import method off the bat.

**Comment by benjaminhr** [comment]
I think it should be fine to use a node unit test framework as all the utils.js file does is create a unique number. And if it's really a problem then you can just ignore it. 

I would rather leave browserify out of this project and keep it lightweight. 
What do you think?

**Comment by jonyeezs** [comment]
@benjaminr177 I can understand, not to test utils as there isn't much need for a test there, pretty cookie cutter code. And yes browserify does add some weight to the build process.

But i suppose there is a benefit if this ever scales and with a more modular structure, it'll be easy to test new code in the future.

Anyways the works been done. If you think it's still too heavy i can drop it :ok_hand:

**Comment by benjaminhr** [comment]
Maybe in the future it would be appropriate to get browserify, etc set up, but for now I think we should just keep it simple.
